version: "3"

services:
  app:
    build: .
    container_name: micro2
    ports:
      - "8000"
    command:
      "npm run start"
    logging:
      options:
        max-size: "10M"
      
networks:
  default:
      name: micro_backend